/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("java-library")
}

dependencies {
    api(libs.org.yaml.snakeyaml)
    api(libs.org.freemarker.freemarker)
    api(libs.mysql.mysql.connector.java)
    compileOnly(libs.org.projectlombok.lombok)
    annotationProcessor(libs.org.projectlombok.lombok)
    api(libs.org.mybatis.generator.mybatis.generator.core)
}

description = "ocean-codegen"
//version = libs.versions.project.version.get()