/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("java-library")
}

dependencies {
    api(libs.org.springframework.boot.spring.boot.starter.web)
    api(project(":common-utils"))
//    api(libs.org.springframework.cloud.spring.cloud.starter.openfeign)

    api(libs.org.hibernate.validator.hibernate.validator)
    api(libs.org.springframework.boot.spring.boot.starter.validation)
    api(libs.com.alibaba.transmittable.thread.local)
    compileOnly(libs.org.projectlombok.lombok)
    annotationProcessor(libs.org.projectlombok.lombok)
}

description = "ocean-web"
//version = libs.versions.project.version.get()