/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("java-library")
}

dependencies {
    api(libs.org.springframework.boot.spring.boot.starter.data.redis)
    api(project(":common-utils"))
    implementation(libs.org.springframework.boot.spring.boot.starter.web)
    implementation(libs.org.springframework.boot.spring.boot.starter.aop)
}

description = "common-cache"
//version = libs.versions.project.version.get()