/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "oceanframework"
val version: String by settings
val group: String by settings

gradle.beforeProject {
    this.group = group
    this.version = version
}

include(":ocean-log")
include(":common-utils")
include(":common-auth")
include(":ocean-codegen")
include(":ocean-web")
include(":ocean-webflux")
//include(":ocean-security")
include(":common-cache")
//include(":ocean-geo")

pluginManagement {
    repositories {
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    rulesMode = RulesMode.PREFER_PROJECT
    repositories {
        mavenCentral()
        maven {
            url = uri("https://maven.aliyun.com/repository/public/")
        }
        maven {
            url = uri("https://maven.aliyun.com/repository/central")
        }

        maven {
            url = uri("https://repo.maven.apache.org/maven2")
        }

    }


}


