/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("java-library")
}

dependencies {
    api(libs.org.geotools.gt.main)
    api(libs.org.geotools.gt.referencing)
    api(libs.org.geotools.gt.epsg.wkt)
    api(libs.com.google.guava.guava)
    api(libs.com.alibaba.fastjson)
    testImplementation(libs.org.junit.jupiter.junit.jupiter)
    testImplementation(libs.org.junit.platform.junit.platform.runner)
    testImplementation(libs.org.junit.platform.junit.platform.launcher)
    testImplementation(libs.org.junit.platform.junit.platform.console.standalone)
}

description = "ocean-geo"
