/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("java-library")
//    id("maven-publish")
}

dependencies {
    api(libs.org.springframework.boot.spring.boot.starter.oauth2.resource.server)
    api(project(":ocean-web"))
    api(project(":common-utils"))
    api(libs.org.springframework.boot.spring.boot.starter.data.redis)
    compileOnly(libs.org.projectlombok.lombok)
    annotationProcessor(libs.org.projectlombok.lombok)
}

description = "common-auth"
//version = libs.versions.project.version.get()

//
//publishing {
//    repositories {
//        mavenLocal()
//    }
//    publications {
//        create<MavenPublication>("mavenJava") {
//            from(components["java"])
//            artifactId = project.name
//        }
//    }
//}