/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("java-library")
}

dependencies {
    api(libs.org.slf4j.slf4j.api)
    implementation(libs.ch.qos.logback.logback.classic)
}

description = "ocean-log"
version = libs.versions.project.version.get()