/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("java-library")
}

dependencies {
    api(libs.org.springframework.boot.spring.boot.starter.webflux)
    api(project(":common-utils"))
    api(libs.org.springframework.cloud.spring.cloud.starter.openfeign)
    api(libs.org.hibernate.validator.hibernate.validator)
    api(libs.org.springframework.boot.spring.boot.starter.validation)
    testImplementation(libs.junit.junit)
    compileOnly(libs.org.projectlombok.lombok)
}

description = "ocean-webflux"
//version = libs.versions.project.version.get()