/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("java-library")
}



dependencies {
    implementation(libs.org.springframework.spring.context)
    api(libs.org.apache.commons.commons.lang3)
    api(libs.org.bouncycastle.bcprov.jdk18on)
    api(libs.commons.codec.commons.codec)
    api(libs.com.google.guava.guava)
    api(libs.org.mapstruct.mapstruct.processor)
    api(libs.org.mapstruct.mapstruct)
    api(libs.cn.hutool.hutool.core)
    api(libs.com.google.code.gson.gson)
    compileOnly(libs.org.projectlombok.lombok)
    annotationProcessor(libs.org.projectlombok.lombok)

}



description = "common-utils"
//version = libs.versions.project.version.get()

